apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: ray-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray-manager
  namespace: system
  labels:
    control-plane: ray-manager
spec:
  selector:
    matchLabels:
      control-plane: ray-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: ray-manager
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: bonsaidev.azurecr.io/bonsaidev/ray-operator:0.1.0
        name: ray-manager
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      terminationGracePeriodSeconds: 10
